application: amrellabban
version: live
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

handlers:

- url: /crossdomain.xml
  static_files: crossdomain.xml
  upload: crossdomain.xml

- url: /resources
  static_dir: resources

- url: /
  static_files: static/home.html
  upload: static/home

- url: /(.*)/
  static_files: static/\1.html
  upload: static/(.*)/

- url: /(.*)
  static_files: static/\1.html
  upload: static/(.*)
